version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "3001:3001"

  ip-viewer-app:
    build:
      context: ./ip-viewer-app
      dockerfile: App.Dockerfile
    ports:
      - "3000:3000"